# Generated by Django 4.2.7 on 2023-11-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breweries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.FloatField(max_length=10)),
                ('name', models.TextField()),
                ('style', models.TextField()),
                ('ounces', models.IntegerField()),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brewery_beers', to='Listbeers.breweries')),
            ],
        ),
    ]
