# Generated by Django 4.2.7 on 2023-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listbeers', '0002_alter_beer_abv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
