# Generated by Django 4.2.7 on 2023-11-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listbeers', '0003_alter_beer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='ounces',
            field=models.FloatField(),
        ),
    ]
