# Generated by Django 4.2.7 on 2023-11-13 10:13

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Breweries = apps.get_model("Listbeers", "Breweries")
    for brewerie in Breweries.objects.all():
        brewerie.city = brewerie.city +","+brewerie.state
        brewerie.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):


    dependencies = [
        ('Listbeers', '0004_alter_beer_ounces'),
    ]

    operations = [
        migrations.RunPython(forwards_func,reverse_func),

        migrations.RemoveField(
            model_name='breweries',
            name='state',
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.TextField(),
        ),
    ]
